name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: piki/clip@eabcd64af154718f42ae14bed398b252ba4825ca

    - name: apt install dependencies
      run: sudo apt update && sudo apt install --no-install-recommends -y make gcc libalut-dev libsdl-ttf2.0-dev libsdl-image1.2-dev

    - name: make
      run: make
